### ISSUE TITLE
Check whether Fujitsu YANG modules are processed

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/sdo_analysis#10]
Check whether the daily import from YangModels works for the brand new
https://github.com/YangModels/yang/tree/master/vendor

**Comment by miroslavKovacPantheon** [comment]
they are not. Waiting for them to add the patform-metadata.json file. that way they will be processed automatically.. they said they are working on it so still waiting for that.

But interestingly not even new cisco models are parsed and no compilation results with them. because we have static path for each of the xe/ xr/ nx/ versions and .. we should resolve this by code. I am creating new issue for that.

**Comment by miroslavKovacPantheon** [comment]
Opened issue [here](https://github.com/YangCatalog/sdo_analysis/issues/11)

**Comment by miroslavKovacPantheon** [comment]
These modules are processed above issue closed as well. You can check this out at [yangcatalog private page](https://yangcatalog.org/private)
