### ISSUE TITLE
validators not up to date

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/sdo_analysis#21]
Hi,

The yangcatalog still uses pyang 1.7.5, while 2.0 is out.
We need a mechanism to automatically upgrade pyang, yanglint, yumaworks, confd, when avail.
+ a way to re-run the validation on the newest models.

Regards, B.

**Comment by miroslavKovacPantheon** [comment]
I don t think we should do automatic updates. Especialy with pyang it is a problem. With new api a lot will change and therefore the code might be broken.

This is why I suggest that with every release we should try to update validators as well. yanglint would be easy pyang will break the code and therefore we need to update code as well yangdump-pro can t be done automatically because one has to be logged in on their page and download it manually. Confd is not for free.

**Comment by evyncke** [comment]
ConfD premium is for free as IETF was granted a free license by Cisco for YC.O (extended to all contractors working on YC.O).

Else, I agree that most of those packages cannot really be trusted to be backward compatible...

-éric

**Comment by miroslavKovacPantheon** [comment]
Closing this because we have updated all the validators but confd. Waiting for cisco and tailf to give us new version of that. Nothing we can do about it now
